OdeTofood/Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeTofood.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        German,
        Romanian
    }
}

OdeTofood/Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace OdeTofood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name="Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }


        public CuisineType Cuisine { get; set; }
    }
}

OdeTofood/ViewModels/HomeIndexViewModel.cs
using OdeTofood.Models;
using System.Collections.Generic;

namespace OdeTofood.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

OdeTofood/ViewModels/RestaurantEditModel.cs
using OdeTofood.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OdeTofood.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }

        public CuisineType Cuisine { get; set; }
    }
}

OdeTofood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace OdeTofood.Controllers
{
    //route attributes
    
    //request /about
    //[Route("about")]
    [Route("company/[controller]/[action]")] //controller token
    public class AboutController
    {
        //if its empty its like a default
        //[Route("")]
        public string Phone()
        {
            return "1+555+555+5555";
        }

        //[Route("address")]
        //[Route("[action]")] //action token
        public string Address()
        {
            return "USA";
        }
    }
}

OdeTofood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OdeTofood.Models;
using OdeTofood.Services;
using OdeTofood.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeTofood.Controllers
{
    public class HomeController : Controller
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;
        #region GOOD WHEN WE BUILD API
        /*
        public IActionResult Index()
        {
            var model = new Restaurant
            {
                Id = 1 ,
                Name = "Scott's Pizza Place"
            };

            //this returns JSON. Good for APIS
            return new ObjectResult( model );
        }
        */
        #endregion

        public HomeController( IRestaurantData restaurantData ,
                              IGreeter greeter )
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        public IActionResult Index()
        {
            var model = new HomeIndexViewModel
            {
                Restaurants = _restaurantData.GetAll() ,
                CurrentMessage = _greeter.GetMessageOfTheDay()
            };

            //by default its looking after Views folder compared to the controller/model where the name doesn't matter
            //if this is being returned in the Index() method, then its gonna look for Index.cshtml
            return View( model );
        }

        public IActionResult Details( int id )
        {
            var model = _restaurantData.Get( id );
            if ( model is null )
            {
                ////return a http response with 404. its good with API
                //return NotFound();

                return RedirectToAction( nameof( Index ) );
            }
            return View( model );
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( RestaurantEditModel model )
        {
            //ModelState.IsValid we check if is properly populated based on the data notation
            if ( ModelState.IsValid )
            {
                var newRestaurant = new Restaurant
                {
                    Name = model.Name ,
                    Cuisine = model.Cuisine
                };

                newRestaurant = _restaurantData.Add( newRestaurant );

                return RedirectToAction( nameof( Details ) , new { id = newRestaurant.Id } );
            }
            else
            {
                return View();
            }

        }
    }
}

OdeTofood/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeTofood.Services;

namespace OdeTofood.Pages
{
    public class GreetingModel : PageModel
    {
        private readonly IGreeter _greeter;

        public string CurrentGreeter { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public void OnGet(string name)
        {
            CurrentGreeter = $"{name} : {_greeter.GetMessageOfTheDay()}";
        }
    }
}

OdeTofood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeTofood.Models;
using OdeTofood.Services;

namespace OdeTofood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel( IRestaurantData restaurantData )
        {
            _restaurantData = restaurantData;
        }

        public IActionResult OnGet(int id)
        {
            Restaurant =  _restaurantData.Get( id );

            if(Restaurant == null )
            {
                return RedirectToAction( "Index" , "Home" );
            }
            return Page();//similar to return view
        }

        public IActionResult OnPost(  )
        {
            if ( ModelState.IsValid )
            {
                _restaurantData.Update( Restaurant );
                return RedirectToAction( "Details" , "Home" , new { id = Restaurant.Id } );
            }

            return Page();
        }
    }
}

OdeTofood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeTofood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeTofood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private readonly IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();
            //if we have View(model) and the model is a string, ./net core will go out there looking for a Scott/iustin etc .cshtml
            return View("Default", model);
        }
    }
}

OdeTofood/Pages/Greeting.cshtml
@page "{name}" 

@*@inject IGreeter Greeter;
<div>@Greeter.GetMessageOfTheDay()</div>*@


@*it's the cs file for this class*@
@model GreetingModel

<div> @Model.CurrentGreeter </div>

OdeTofood/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeTofood.Pages.Restaurants

@model EditModel

<h1>Editi @Model.Restaurant.Name</h1>

<form method="post">
    
    <input type="hidden" asp-for="Restaurant.Id"/>
    
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>

    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>

    </div>

    <input type="submit" name="save" value="Save" />
</form>

OdeTofood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection( "footer" , required: false )
    </footer>
</body>
</html>

OdeTofood/Views/Home/Create.cshtml
@using OdeTofood.Models
@model Restaurant

@{ 
    ViewBag.Title = "Create";
}
<h1>Create</h1>

<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>

    </div>

    <input type="submit" name="save" value="Save" />
</form>

OdeTofood/Views/Home/Details.cshtml
@model Restaurant
@*avoid using if here*@
@*@if ( Model == null )
    {
        <div>not found my friend</div>
    }
    else
    {

        <h1>@Model.Name</h1>

        <div> ... details ...</div>
    }*@

@{ 
    ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>
<div>
    Id: @Model.Id
</div>
<div>
    Cuisine: @Model.Cuisine
</div>
<a asp-action="Index" asp-controller="Home">Home</a>

OdeTofood/Views/Home/Index.cshtml
@model OdeTofood.ViewModels.HomeIndexViewModel

@{
    ViewBag.Title = "Home page";

    //we can overwrite the layout from viewstart in other cshtml page

    //Layout = "~/Views/Shared/_Layout2.cshtml";
    //Layout = null
}

<h1>All restaurants</h1>

@foreach ( var restaurant in Model.Restaurants )
{
    //PARTIAL CLASS
    @Html.Partial("_Summary", restaurant)
}


<div>
    <a asp-action="Create">Add Restaurant</a>
</div>

OdeTofood/Views/Home/_Summary.cshtml
@model Restaurant

<section>
    <h3>@Model.Name</h3>
    <div>
        Cuisine: @Model.Cuisine
    </div>
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>

</section>

OdeTofood/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

OdeTofood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection( "footer" , required: false )
        <vc:greeter></vc:greeter>
    </footer>
</body>
</html>